### ISSUE TITLE
LTI Documentation Unclear

### ISSUE THREAD

**Issue by Joeyn1993** [hkhosrav/RiPPLE-Core#132]
LTI documentation is unclear.

The fields referred to in the docs do not match the fields in the linked launcher tool.

Should clearly state what info needs to go in the code, and what info must be provided to the launcher.

**Comment by CaptainAchilles** [comment]
Hey @Joeyn1993; I made some changes to [Ripple-Workflow]](https://github.com/hkhosrav/RiPPLE-Core/wiki/RiPPLE-Workflow). Could you review it and let me know if there is anything else which needs to be added.

**Comment by Joeyn1993** [comment]
Looks good to me
