### ISSUE TITLE
Engagement Graph Clutter

### ISSUE THREAD

**Issue by johnnguyen1997** [hkhosrav/RiPPLE-Core#134]
At the current iteration, the graphs in the engagement tab contains over 10 elements with some elements having very little relevance with each other.

I suggest that the graphs should be split into multiple graphs.

E.g. Questions Asked, Answered and Viewed should be its own graph.

**Comment by CaptainAchilles** [comment]
In the latest version of RiPPLE; the engagement page only allows visualiztion with a `RadarChart`

**Comment by johnnguyen1997** [comment]
Alright sounds good
