### ISSUE TITLE
Sorting on 'created time' does not work

### ISSUE THREAD

**Issue by CaptainAchilles** [hkhosrav/RiPPLE-Core#139]
Sorting on `created time` causes the server to fail. 

Related to #138?

I guess a review of all question sorting and unit tests would be the best way to solidify this functionality.

**Comment by johnnguyen1997** [comment]
When looking at the search request, it appears that it is looking for the "created" field. Based on the error message, it seems that the creation date is not stored. As a result, sorting by created date does not seem to be possible in the present moment.

**Comment by CaptainAchilles** [comment]
## Sort By
`comments` and `personalisation` apply no sort order since they are unimplemented.

## Filter Field
`unanswered`, `answered`, `wrong` all apply filters for a hard-coded user_id of `2`. This can be fixed by passing in the current user session object and applying an aggregate based on that.

## Search
The freetext text_search field should also search question topics as uncovered in a UX study.
