### ISSUE TITLE
Question Responses Reformat on Click

### ISSUE THREAD

**Issue by Joeyn1993** [hkhosrav/RiPPLE-Core#146]
Question responses are initially wrapped in a label, on click the label disappears and the responses reformat.

**Comment by CaptainAchilles** [comment]
Addressed changes by ensuring the checkbox and `letter index` are on their own line. Tested by using some questions and everything looks good.

![image](https://user-images.githubusercontent.com/16090868/33053291-7c901760-cebe-11e7-9fd6-742013048f06.png)
