### ISSUE TITLE
Invalid Image Save

### ISSUE THREAD

**Issue by Joeyn1993** [hkhosrav/RiPPLE-Core#147]
#137 

Update allowing images to be served in production modified workflow of image validation/save.

An image with the wrong extension now returns null from util.py, but this is not handled anywhere else.

**Comment by CaptainAchilles** [comment]
Hey @Joeyn1993; I wrapped the question authoring inside of a database transaction. This will also address the issues we were having with questions which were missing responses. The transaction will rollback on an `IntegrityError`; which is in turn throw if the image is not valid.
