### ISSUE TITLE
Client behaviour after correct answer

### ISSUE THREAD

**Issue by Joeyn1993** [hkhosrav/RiPPLE-Core#169]
After answering a question correctly the client appends the explanation to the bottom of the page.

If the question + answers are more than a screen high, this is not obvious to the user. 

The next button is also always displayed so the user may move to the next question without noticing the explanation.

**Comment by CaptainAchilles** [comment]
Would scrolling to the question explanation be an adequate action to take after answering?

**Comment by Joeyn1993** [comment]
Scrolling on correct answer was my initial thought, but the number (%) of answers for each option is also important information.

Maybe add a tab for explanation at the bottom of the page, scroll to that, and the user can click on that if they want the explanation? Or is that getting too complex

**Comment by CaptainAchilles** [comment]
We will implement as scrolling to the bottom of the page; UX tests will help determine if this approach is adequate.
