### ISSUE TITLE
Bullet Chart to Show competency progress

### ISSUE THREAD

**Issue by CaptainAchilles** [hkhosrav/RiPPLE-Core#17]
![image](https://user-images.githubusercontent.com/16090868/28301396-9ffe8892-6bc9-11e7-923c-aa8a69f18985.png)

A bullet chart could be a good way to visualize the user progress in the context of their goals. They are suitable because:
* Compact
* Show a discrete point (Their users goal)
* Show the users progress
* Show different ranges (needs improvement, good progress, outstanding progress)

**Comment by MrCeleryman** [comment]
Can we move this one to High Priority please?
