### ISSUE TITLE
Leaderboard Person Display

### ISSUE THREAD

**Issue by Joeyn1993** [hkhosrav/RiPPLE-Core#173]
The leaderboard page should display the top X + the current user (and their position)

**Comment by CaptainAchilles** [comment]
As per stakeholder input:

> (1) Leaders board: I think the leader board is still using some fake data am I right? It would be great if we could have the following columns: questions contributed, questions answered, questions answered correctly (first response), questions rated, badges achieved. The same info to be available for instructor in admin page.

**Comment by Joeyn1993** [comment]
#248 addresses @CaptainAchilles  comment with new columns.

**Comment by Joeyn1993** [comment]
Fixed tests. Current user highlighted in table
