### ISSUE TITLE
Aggregate Competency causing key error

### ISSUE THREAD

**Issue by Joeyn1993** [hkhosrav/RiPPLE-Core#185]
When running client+server seeded with CPSC304.json the server throws error error:

`File "\ripple\ripple-core\server\src\users\services\UserService.py", line 124, in _group_competencies
    carry[c.topics].append(c)`
`KeyError: <django.db.models.fields.related_descriptors.create_forward_many_to_many_manager.<locals>.ManyRelatedManager object at 0x00000268FC325CF8>`

**Comment by CaptainAchilles** [comment]
Fixed in #184
