### ISSUE TITLE
Achievements should notify user when complete

### ISSUE THREAD

**Issue by Joeyn1993** [hkhosrav/RiPPLE-Core#188]
Users should be told when they finish an achievement

**Comment by CaptainAchilles** [comment]
Relates to #194

**Comment by Joeyn1993** [comment]
44fc2a6

Notification support added in server.
Achievement notifications moved into new notification module.

Middleware stack:
Cors -> Django -> TokenValidator -> TokenValidator -> NotificationMiddleware -> AchievementChecker
