### ISSUE TITLE
Add topic filtering into SearchMenu component

### ISSUE THREAD

**Issue by CaptainAchilles** [hkhosrav/RiPPLE-Core#193]
Usability testing has revealed that the topic filtering on the `VariableDataVisualiser` component is too abstract/far removed from interacting with the question searching.

The topic filtering should be added to the SearchMenu component

**Comment by zicozico77** [comment]
![image](https://user-images.githubusercontent.com/13598993/33462978-731b65e8-d686-11e7-88d7-ae5801aafd2e.png)

also need a typo fix, should be `Visualize`
