### ISSUE TITLE
Allow users to edit questions

### ISSUE THREAD

**Issue by Joeyn1993** [hkhosrav/RiPPLE-Core#207]
Users should be able to edit their own questions

Instructors should be able to edit all questions

**Comment by Joeyn1993** [comment]
Do we want to archive the old versions of questions? @CaptainAchilles

**Comment by Joeyn1993** [comment]
Server side complete  48ba220

**Comment by CaptainAchilles** [comment]
Yes; I think keeping a question history is important.

**Comment by Joeyn1993** [comment]
Active tag in the model would probably be the best way to deal with this then

**Comment by CaptainAchilles** [comment]
Would it be too much work to preserve the history? I only think we should keep it as a record of proof that a question _was_ on grounds to be reportable after it has been amended.

**Comment by Joeyn1993** [comment]
Question history table + endpoint needed

**Comment by CaptainAchilles** [comment]
I'll handle the client side of things for this pending the TinyMCE changes from #211

**Comment by Joeyn1993** [comment]
Question previews now in #224

**Comment by CaptainAchilles** [comment]
As discussed the question previewing is now in your hands @Joeyn1993 
Changes required:
* Update author routes to be
    * `/author/new/`
    * /`author/edit/:id`
* Add `AuthorWrapper` component to wrap the `AuthorView`
* Update `AuthorView` to accept an `IQuestionBuilder` as input rather than creating its own.
