### ISSUE TITLE
Add consent form functionality

### ISSUE THREAD

**Issue by Joeyn1993** [hkhosrav/RiPPLE-Core#211]
Users must respond to a consent form

**Comment by Joeyn1993** [comment]
c616072

Front and back ends connected

Users must respond to a consent form before they are allowed to use the system

Need to include consent form in course creation (provide a default?)

Check instructor interactions.

**Comment by CaptainAchilles** [comment]
I'll add the default consent form data in this morning

**Comment by CaptainAchilles** [comment]
Consent form is now required for courses. If one does not exist the user will be told and unable to use the site. A default consent form is provided to instructors, but it is not active by default.
