### ISSUE TITLE
Next Question button should be based on a recommendation of some sort

### ISSUE THREAD

**Issue by Joeyn1993** [hkhosrav/RiPPLE-Core#229]
Next Question currently pulls a completely random question
- could be already answered
- could be inappropriate given their progress
- should be based off some sort of recommendation

**Comment by hkhosrav** [comment]
it can be based on the current search criteria (i.e., the next question that would have been displayed on the question repository page)

**Comment by Joeyn1993** [comment]
System added in #245 
Using an ELO system for both users & questions

"skip question" button gives a random question out of the best 5 options. If there aren't 5 options it gives a random question.

Future:
Completely Hidden from users currently - could be shown on the question page and/or put into leaderboard?

Recommended search could be implemented?
