### ISSUE TITLE
Create graphs with d3

### ISSUE THREAD

**Issue by zicozico77** [hkhosrav/RiPPLE-Core#360]
Should attempt to create the treemap with d3 as this is bound to work on deployment as well.

**Comment by Joeyn1993** [comment]
@zicozico77 is this done?

**Comment by zicozico77** [comment]
Treemap has been added and given that the scales issue of the radar chart was fixed it no longer requires being built in d3. However, have not made the treemap update on topic change yet, so will close when that feature is working
