### ISSUE TITLE
competency graph is reloading slowly from server

### ISSUE THREAD

**Issue by hkhosrav** [hkhosrav/RiPPLE-Core#376]
Some of the functionality can be moved to client side to speed up the process

**Comment by zicozico77** [comment]
Getting rid of the loop that calculates the average for the permutations for all competencies with two topics cuts the load time from my last network time of 1.5s to 500ms so about a third. Would be significantly better for requests with more topics as the combination factor makes it scale exponentially the more topics it has.

There is a lot of infrastructure related to permutations, such as the IEdges models that could be removed, the only thing I believe is actually using it is the topic dependency chart. Removing it will make this chart meaningless however.

**Comment by Joeyn1993** [comment]
Resolved
