### ISSUE TITLE
Refactor Topics + offerings

### ISSUE THREAD

**Issue by Joeyn1993** [hkhosrav/RiPPLE-Core#410]
Add in university->course->offering

offerings have topics

Same topic can be used between courses

**Comment by Joeyn1993** [comment]
Admin Topic Stuff:
1. Duplicates
2. Click to select topic on import 
3. Rename

**Comment by hkhosrav** [comment]
Remove course topic from initial pop up for creating a course

**Comment by hkhosrav** [comment]
Add renaming ability under modify topics

**Comment by hkhosrav** [comment]
Try to get rid of save button and save changes as they occur

**Comment by Joeyn1993** [comment]
Pushed into dev

Saving still needs thinking about

**Comment by Joeyn1993** [comment]
Topics on existing questions being deleted??
